### ISSUE TITLE
scholdoc-citeproc fails with custom latex commands

### ISSUE THREAD

**Issue by lionel-** [timtylin/scholdoc-citeproc#1]
Hello,

When custom latex commands are defined in `default.latex`, scholdoc-citeproc fails with an error:

```
! Undefined control sequence.
l.85 \mycustomcommand
```

This does not happen with pandoc-citeproc.

**Comment by lionel-** [comment]
Sorry I was confused while looking for the source of the bug.

The culprit is the `markdown_scholarly` reader.

**Comment by lionel-** [comment]
The right template to edit is `scholmdTemplate.latex`. I wrongly assumed it was using `default.latex`.

**Comment by timtylin** [comment]
Looks like it is high-time to finish that "Scholdoc for Pandoc users" page I've been putting off for a while.
